---
- hosts: frontend
  become: yes
  remote_user: ubuntu
  become_method: sudo
  vars:
    - ansible_python_interpreter: /usr/bin/python3

  roles:
    - role: ../roles/misc
      tags:
        - vendor
        - misc
    - role: geerlingguy.git
      tags:
        - vendor
        - git
    - role: geerlingguy.ntp
      tags:
        - vendor
        - ntp
    - role: geerlingguy.nginx
      tags:
        - app
        - nginx
    - role: ../roles/h5bp
      tags:
        - app
        - nginx
    - role: geerlingguy.php
      tags:
        - app
        - php
    - role: geerlingguy.nodejs
      tags:
        - app
        - nodejs
    # - role: ../roles/angular-pm2
    #   tags:
    #     - app
    #     - nodejs
