---
- name: update yum cache
  yum: name=* state=latest update_cache=yes

- name: Install prerequisites
  yum: >
    name={{ item }}
    state=present
  with_items:
    - vim
    - telnet

- name: Ensure the OS already has swap partition
  script: swapfile.sh

- name: Ensure the SSH key is generated
  command: ssh-keygen -t rsa -f /home/centos/.ssh/id_rsa -N ''
  args:
    creates: /home/centos/.ssh/id_rsa

- name: Download the generated SSH key
  fetch:
    src: "/home/centos/.ssh/id_rsa.pub"
    dest: "../data/ssh-keys/{{ inventory_hostname }}_id_rsa.pub"
    flat: yes
